# Config for hosting via https://netlify.com
[build]
  publish = "public"
  command = "hugo && (cd scripts/seo-image-gen && go run main.go)"

# Handle 404s with a pretty page
[[redirects]]
  status = 404
  from = "/*"
  to = "/404.html"